Repository eslint/eslint-scope, pull requests merged in 2021-07, with the labels that each got.

#69 Update: support class fields (refs eslint/eslint#14343)
  lib/referencer.js
  lib/scope-manager.js
  lib/scope.js
  package.json
  tests/class-fields.js
Labels: triage

#71 Breaking: Switch to ESM (fixes #70)
  .editorconfig
  .eslintrc.cjs
  .eslintrc.js
  .github/workflows/ci.yml
  .gitignore
  Makefile.js
  README.md
  lib/definition.js
  lib/index.js
  lib/pattern-visitor.js
  lib/reference.js
  lib/referencer.js
  lib/scope-manager.js
  lib/scope.js
  lib/variable.js
  lib/version.js
  package.json
  rollup.config.js
  tests/arguments.js
  tests/catch-scope.js
  tests/child-visitor-keys.js
  tests/class-fields.js
  tests/commonjs.cjs
  tests/es6-arrow-function-expression.js
  tests/es6-block-scope.js
  tests/es6-catch.js
  tests/es6-class.js
  tests/es6-default-parameters.js
  tests/es6-destructuring-assignments.js
  tests/es6-export.js
  tests/es6-import.js
  tests/es6-iteration-scope.js
  tests/es6-new-target.js
  tests/es6-object.js
  tests/es6-rest-args.js
  tests/es6-super.js
  tests/es6-switch.js
  tests/es6-template-literal.js
  tests/export-star-as-ns-from-source.js
  tests/fallback.js
  tests/function-expression-name.js
  tests/get-declared-variables.js
  tests/global-increment.js
  tests/implicit-global-reference.js
  tests/implied-strict.js
  tests/label.js
  tests/nodejs-scope.js
  tests/object-expression.js
  tests/optimistic.js
  tests/references.js
  tests/typescript.js
  tests/util/espree.js
  tests/with-scope.js
  tools/update-version.js
Labels: accepted, breaking change

#73 Fix: Ensure correct version in package
  .github/workflows/ci.yml
  .gitignore
  lib/version.js
  package.json
Labels: accepted, bug
