Repository eslint/eslint-scope, pull requests merged in 2021-11, with the labels that each got.

#79 build: upgrade eslint-release to v3.2.0 to support conventional commits
  package.json
Labels: accepted

#80 feat!: support class static blocks
  lib/referencer.js
  lib/scope-manager.js
  lib/scope.js
  package.json
  tests/class-static-blocks.js
Labels: enhancement, accepted

#81 feat: Add sourceType:commonjs support
  lib/index.js
  lib/scope-manager.js
  tests/nodejs-scope.js
Labels: enhancement
