Repository eslint/eslint-scope, pull requests merged in 2024-01, with the labels that each got.

#115 feat!: Require Node.js ^18.18.0 || ^20.9.0 || >=21.1.0
  .github/workflows/ci.yml
  package.json
Labels: feature, breaking

#116 fix!: class `extends` is evaluated in the class scope
  lib/referencer.js
  tests/es6-class.js
  tests/es6-super.js
Labels: bug, accepted, breaking

#118 feat!: use ESTree `directive` property when searching for `"use strict"`
  lib/index.js
  lib/scope-manager.js
  lib/scope.js
  tests/use-strict.js
Labels: bug, accepted, breaking change, feature, breaking
