Repository eslint/eslint-scope, pull requests merged in 2024-03, with the labels that each got.

#119 chore: upgrade espree@10.0.1, eslint-visitor-keys@4.0.0
  package.json
Labels: chore

#121 refactor: switch to eslint flat config
  .eslintignore
  .eslintrc.cjs
  Makefile.js
  eslint.config.js
  lib/index.js
  lib/pattern-visitor.js
  lib/referencer.js
  lib/scope-manager.js
  lib/scope.js
  package.json
  tests/arguments.js
  tests/catch-scope.js
  tests/es6-arrow-function-expression.js
  tests/es6-block-scope.js
  tests/es6-catch.js
  tests/es6-class.js
  tests/es6-default-parameters.js
  tests/es6-destructuring-assignments.js
  tests/es6-import.js
  tests/es6-iteration-scope.js
  tests/es6-new-target.js
  tests/es6-object.js
  tests/es6-rest-args.js
  tests/es6-switch.js
  tests/es6-template-literal.js
  tests/function-expression-name.js
  tests/get-declared-variables.js
  tests/global-increment.js
  tests/implied-strict.js
  tests/label.js
  tests/nodejs-scope.js
  tests/references.js
  tests/typescript.js
  tests/util/ecma-version.js
  tests/with-scope.js
Labels: accepted, chore

#122 docs: document Security Policy
  README.md
Labels: security, documentation
